language: ruby
bundler_args: --without production doc
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - LC_ALL=en_US.UTF-8
  - LANG=en_US.UTF-8
services:
  - postgresql

before_script:
  - psql -c 'create database matchy_test;' -U postgres

notifications:
  email:
    - info@christophbuente.de
