language: ruby
cache:
- bundler
sudo: false
rvm:
- 2.1.4
- 2.2.2
services:
- postgresql
before_script:
- psql -c 'create database poichecker_test;' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -U postgres -d poichecker_test
- psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d poichecker_test
- psql -U postgres -q -d poichecker_test -f db/structure.sql
notifications:
  email:
  - info@christophbuente.de
  slack:
    secure: nvJvdjPBV3Zlh7AVSlZcH94/fVxFwAwI/vGzMlZnsgfs7Z2pweqn0PF5wU4UA5IhLvfaNaxUaiQLX5Qdyn5LhY+Jsj/Bwxu2LBtrMxyKYGw2revhl5sQoaKTIPOik5wN61qRfTCx942N12Q7gZi0gslu5FdHAUK0xWhy7YJHDwI=
