language: ruby
cache:
  - bundler
  - apt

bundler_args: --without development production doc --deployment --jobs=3 --retry=5

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2

services:
  - postgresql

before_script:
  - sudo locale-gen de_DE
  - sudo update-locale LANG=de_DE
  - psql -c 'create database matchy_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d matchy_test
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d matchy_test
  - psql -U postgres -q -d matchy_test -f db/structure.sql"

branches:
  only:
    - master

notifications:
  email:
    - info@christophbuente.de
